# Generated by Django 2.1.7 on 2019-02-12 03:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hewan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('species', models.TextField(max_length=255)),
                ('berat', models.CharField(max_length=1)),
                ('umur', models.TextField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='kandang',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
                ('isi_kandang', models.TextField(max_length=255)),
                ('luas_kandang', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='pengunjung',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=25)),
                ('hari_berkunjung', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='penjaga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.TextField(max_length=255)),
                ('nomor_telepon', models.CharField(max_length=25)),
                ('jadwal_jaga', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
